Gene identifier/annotation fixes
mibig-secmet/mibig-json pull request #192
Opened 2022-05-17 12:56 UTC by SJShaw

Removes all `No gene ID` identifiers, replacing them with valid identifiers if possible or removing the fields if not.

Removes or corrects all duplications of genes in gene annotations, as the identifier should be unique, The validator script should now prevent new cases of this appearing.

Corrected, and forbidden in the schema for future cases, any gene identifiers containing trailing or leading whitespace.

Fixes a batch of entries where the polyketide module gene list was a single string containing comma separated gene names instead of being an actual list of strings. The schema has changed to forbid commas in any gene names in that list. Commas remain in the gene annotations `name` field for some entries, but will be handled later on.

2022-05-19 09:04 UTC, kblin requested changes
Apart from the extra newline in the schema, 👍 from me.

2022-05-19 09:04 UTC, kblin commented on schema.json
> -}
Whitespace change

2022-05-19 14:35 UTC, SJShaw commented
I've a branch ready that rebases this on top of #193, so it should wait until that's merged.

2022-05-20 09:20 UTC, kblin commented
Ok, #193 is merged, I'm happy to look over the rebased branch again.

2022-05-24 07:13 UTC, kblin approved these changes
Looks good to me 👍

2022-05-24 07:13 UTC, merged